# Generated by Django 4.2.3 on 2023-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_image_code_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
    ]
