# Generated by Django 4.2.4 on 2023-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_size_category_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(null=True, to='base.color'),
        ),
    ]
